version: "3.8"
services:
  nginx:
    image: divadsn/nginx-rtmp-ffmpeg:latest
    restart: unless-stopped
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./wwwdata:/var/www/html:ro
    networks:
      default:
        ipv4_address: 172.32.1.2
        aliases:
          - nginx
  dnsmasq:
    image: 4km3/dnsmasq:latest
    restart: unless-stopped
    volumes:
      - ./conf/dnsmasq.conf:/etc/dnsmasq.conf:ro
    cap_add:
      - NET_ADMIN
    networks:
      default:
        ipv4_address: 172.32.1.3
        aliases:
          - dnsmasq
  wireguard:
    image: weejewel/wg-easy:latest
    restart: unless-stopped
    depends_on:
      - dnsmasq
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    environment:
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.44.0.x
      - WG_DEFAULT_DNS=172.32.1.3
      - WG_ALLOWED_IPS=172.32.1.0/24, 10.44.0.1/32
      - WG_PERSISTENT_KEEPALIVE=25
    env_file:
      - ./wireguard.env
    volumes:
      - wireguard-vol:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      default:
        ipv4_address: 172.32.1.4
        aliases:
          - wireguard
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.32.1.0/24
volumes:
  wireguard-vol:
